@startuml
'https://plantuml.com/class-diagram


class TodoList {
    +addItem
    ~title
    ~description
    ~date
    +edit
    +markComplete
    ~completedView
    ~todoView
    +deleteItem
    ~todoView
    ~completedView

}


@enduml